[build-system]
requires = ["setuptools>=80", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "birdy"
authors = [{ name = "Nam-Khanh Tran", email = "khanh29082003@gmail.com" }]
readme = { file = "README.md", content-type = "text/markdown" }
license = { file = "LICENSE" }
dynamic = ["version"]

requires-python = ">=3.12"
dependencies = [
    "torch",
    "torchvision",
    "torchaudio",
    "torchcodec",
    "numpy<2",
    "pillow",
    "tqdm",
    "scikit-learn",
    "pandas",
    "opencv-contrib-python",
    "timm",
]

[project.optional-dependencies]
dev = [
    "jupyter",
    "jupyterlab-code-formatter",
    "jupyterlab_execute_time",
    "jupyterlab-lsp",
    "perspective-python",
    "python-lsp-server[all]",
    "lckr_jupyterlab_variableinspector",
    "matplotlib",
    "plotly",
    "ruff",
    "pytest",
]

[project.scripts]

[tool.setuptools_scm]

[tool.setuptools.packages.find]
where = ["src"]
include = ["*"]
namespaces = false

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["ALL"]
ignore = ["N812", "S101"]
unfixable = ["F401"]

[tool.ruff.lint.pydocstyle]
convention = "google"

ignore-var-parameters = true

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true

[tool.ruff.format]
docstring-code-format = true
